/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Apresentacao.Features.Relatorio;

import Dominio.Fatures.Relatorio.IRelatorioService;
import Dominio.Fatures.Relatorio.Relatorio;
import Dominio.Features.Crianca.Crianca;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class FrameCadastroRelatorio extends javax.swing.JInternalFrame {

    private Crianca crianca;
    private Relatorio relatorio;
    private SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
    private IRelatorioService serviceRelatorio;

    public FrameCadastroRelatorio(IRelatorioService serviceRelatorio) {
        this.serviceRelatorio = serviceRelatorio;
        initComponents();
    }

    public void setCrianca(Crianca crianca) {
        this.crianca = crianca;
        jLabelInformacoesDaCrianca.setText(crianca.toString());
    }

    public Relatorio getRelatorio() throws ParseException {
        relatorio.setAusente(jCheckAusente.isSelected());
        if (!relatorio.isAusente()) {
            relatorio.setTexto(jTextAreaCadastroRelatorio.getText());
        }
        relatorio.setData(df.parse((String) jTextData.getValue()));
        return relatorio;
    }

    public void setRelatorio(Relatorio relatorio) {
        this.relatorio = relatorio;
        jTextAreaCadastroRelatorio.setText(relatorio.getTexto());
        jTextData.setText(df.format(relatorio.getData()));
        jTextData.setValue(relatorio.getData());
        jCheckAusente.setSelected(relatorio.isAusente());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelInformacoesDaCrianca = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextData = new javax.swing.JFormattedTextField();
        jCheckAusente = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaCadastroRelatorio = new javax.swing.JTextArea();
        jButtonCancelarCadatroRelatorio = new javax.swing.JButton();
        jButtonSalvarCadastroRelatorio = new javax.swing.JButton();

        setClosable(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Relatório");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Informações Da Criança: ");

        jLabelInformacoesDaCrianca.setText("Informações a serem carregadas.");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Data:");

        jTextData.setFormatterFactory(new javax.swing.JFormattedTextField.AbstractFormatterFactory() {
            public javax.swing.JFormattedTextField.AbstractFormatter
            getFormatter(javax.swing.JFormattedTextField jf) {
                try{
                    return new javax.swing.text.MaskFormatter("##/##/####");
                } catch (ParseException pe){
                    pe.printStackTrace();
                }
                return null;
            }
        });
        jTextData.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jCheckAusente.setText("Ausente");
        jCheckAusente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckAusenteActionPerformed(evt);
            }
        });

        jTextAreaCadastroRelatorio.setColumns(20);
        jTextAreaCadastroRelatorio.setLineWrap(true);
        jTextAreaCadastroRelatorio.setRows(5);
        jScrollPane1.setViewportView(jTextAreaCadastroRelatorio);

        jButtonCancelarCadatroRelatorio.setText("Cancelar");
        jButtonCancelarCadatroRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarCadatroRelatorioActionPerformed(evt);
            }
        });

        jButtonSalvarCadastroRelatorio.setText("Salvar");
        jButtonSalvarCadastroRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarCadastroRelatorioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jCheckAusente))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButtonCancelarCadatroRelatorio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonSalvarCadastroRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextData))
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelInformacoesDaCrianca, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabelInformacoesDaCrianca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(8, 8, 8)
                .addComponent(jCheckAusente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalvarCadastroRelatorio)
                    .addComponent(jButtonCancelarCadatroRelatorio))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarCadatroRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarCadatroRelatorioActionPerformed
        dispose();    }//GEN-LAST:event_jButtonCancelarCadatroRelatorioActionPerformed

    private void jCheckAusenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckAusenteActionPerformed
        jTextAreaCadastroRelatorio.setEnabled(!jCheckAusente.isSelected());
    }//GEN-LAST:event_jCheckAusenteActionPerformed

    private void jButtonSalvarCadastroRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarCadastroRelatorioActionPerformed
        if (relatorio == null) {
            relatorio = new Relatorio();
            try {
                serviceRelatorio.adicionar(getRelatorio(), crianca);
                JOptionPane.showMessageDialog(null, "Registrado com sucesso!");
                dispose();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
                relatorio = null;
            }
        } else {
            try {
                serviceRelatorio.atualizar(getRelatorio(), crianca);
                JOptionPane.showMessageDialog(null, "Registrado com sucesso!");
                dispose();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        }
    }//GEN-LAST:event_jButtonSalvarCadastroRelatorioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelarCadatroRelatorio;
    private javax.swing.JButton jButtonSalvarCadastroRelatorio;
    private javax.swing.JCheckBox jCheckAusente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelInformacoesDaCrianca;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaCadastroRelatorio;
    private javax.swing.JFormattedTextField jTextData;
    // End of variables declaration//GEN-END:variables
}
